import { fetch } from 'undici';
import { getDb } from '../db';
import { CITY_CONFIGS } from './cityRegistry';

/**
 * Enriches segments that have generic placeholder names (e.g. "Segment Longueuil #14427")
 * with real street names from OpenStreetMap via the Overpass API.
 *
 * Strategy:
 *   1. Download all named roads in the city's bounding box (single Overpass request)
 *   2. Build a spatial grid index of OSM road points → street name
 *   3. For each unnamed segment, find the nearest OSM road and assign its name
 *
 * This only runs once per city — on subsequent calls, segments already have names and are skipped.
 */

const OVERPASS_URL = 'https://overpass-api.de/api/interpreter';

interface OverpassElement {
  type: string;
  id: number;
  tags?: Record<string, string>;
  geometry?: Array<{ lat: number; lon: number }>;
}

interface StreetPoint {
  lat: number;
  lng: number;
  name: string;
}

// Highway types to include (excludes footway, cycleway, path, etc. for road matching)
const HIGHWAY_TYPES = [
  'residential', 'tertiary', 'secondary', 'primary', 'trunk', 'motorway',
  'unclassified', 'service', 'living_street',
  'tertiary_link', 'secondary_link', 'primary_link', 'trunk_link', 'motorway_link',
].join('|');

function buildOverpassQuery(minLat: number, minLng: number, maxLat: number, maxLng: number): string {
  return `[out:json][timeout:120];
way["highway"~"^(${HIGHWAY_TYPES})$"]["name"](${minLat},${minLng},${maxLat},${maxLng});
out body geom;`;
}

/**
 * Simple grid-based spatial index for fast nearest-street lookups.
 * Divides the area into ~200m cells and assigns each OSM road point to a cell.
 */
class SpatialGrid {
  private cells = new Map<string, StreetPoint[]>();
  private cellSize: number;

  constructor(cellSizeDeg = 0.002) {
    this.cellSize = cellSizeDeg;
  }

  private key(lat: number, lng: number): string {
    return `${Math.floor(lat / this.cellSize)},${Math.floor(lng / this.cellSize)}`;
  }

  add(point: StreetPoint): void {
    const k = this.key(point.lat, point.lng);
    let arr = this.cells.get(k);
    if (!arr) {
      arr = [];
      this.cells.set(k, arr);
    }
    arr.push(point);
  }

  /**
   * Find the nearest street name within maxDistDeg degrees of (lat, lng).
   * Searches the target cell and all 8 neighbors.
   */
  nearest(lat: number, lng: number, maxDistDeg = 0.0005): string | null {
    const centerRow = Math.floor(lat / this.cellSize);
    const centerCol = Math.floor(lng / this.cellSize);

    let bestName: string | null = null;
    let bestDist = Infinity;

    for (let dr = -1; dr <= 1; dr++) {
      for (let dc = -1; dc <= 1; dc++) {
        const k = `${centerRow + dr},${centerCol + dc}`;
        const points = this.cells.get(k);
        if (!points) continue;

        for (const p of points) {
          const dlat = p.lat - lat;
          const dlng = p.lng - lng;
          const dist = dlat * dlat + dlng * dlng;
          if (dist < bestDist) {
            bestDist = dist;
            bestName = p.name;
          }
        }
      }
    }

    // Check against max distance threshold (squared)
    if (bestDist > maxDistDeg * maxDistDeg) return null;
    return bestName;
  }

  get size(): number {
    let total = 0;
    for (const arr of this.cells.values()) total += arr.length;
    return total;
  }
}

/**
 * Pattern matching for generic/placeholder segment names that need enrichment.
 * These are names auto-generated by adapters when the source data lacks street names.
 */
function isGenericName(nomVoie: string, segmentId: string): boolean {
  return (
    nomVoie.startsWith('Segment ') ||
    nomVoie.startsWith('Zone ') ||
    nomVoie === segmentId
  );
}

/**
 * Enrich unnamed segments for a single city.
 * Returns the number of segments enriched.
 */
export async function enrichStreetNames(cityId: string): Promise<number> {
  // Skip Montreal (has geobase names) and cities without bounds
  if (cityId === 'montreal') return 0;
  const cityConfig = CITY_CONFIGS.find((c) => c.id === cityId);
  if (!cityConfig?.bounds) return 0;

  const db = getDb();

  // Count segments that still have generic names
  const segments = db
    .prepare(
      `SELECT id, lat, lng, nom_voie FROM street_segments
       WHERE city_id = ? AND lat IS NOT NULL AND lng IS NOT NULL`
    )
    .all(cityId) as Array<{ id: string; lat: number; lng: number; nom_voie: string }>;

  const toEnrich = segments.filter((s) => isGenericName(s.nom_voie, s.id));
  if (toEnrich.length === 0) return 0;

  console.log(`[StreetNames] ${cityId}: ${toEnrich.length} segments need street names`);

  // Download all named streets from OpenStreetMap for this city's bounding box
  const { minLat, maxLat, minLng, maxLng } = cityConfig.bounds;
  const query = buildOverpassQuery(minLat, minLng, maxLat, maxLng);

  const res = await fetch(OVERPASS_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'AlerteDeneigement/1.0 (contact@alerteneige.app)',
    },
    body: `data=${encodeURIComponent(query)}`,
    signal: AbortSignal.timeout(120_000),
  });

  if (!res.ok) {
    throw new Error(`Overpass API responded ${res.status}`);
  }

  const data = (await res.json()) as { elements: OverpassElement[] };
  const ways = data.elements.filter(
    (e) => e.type === 'way' && e.tags?.name && e.geometry && e.geometry.length > 0
  );

  console.log(`[StreetNames] ${cityId}: ${ways.length} named streets from OpenStreetMap`);

  if (ways.length === 0) return 0;

  // Build spatial grid: index every point of every OSM way
  const grid = new SpatialGrid();
  for (const way of ways) {
    const name = way.tags!.name!;
    for (const pt of way.geometry!) {
      grid.add({ lat: pt.lat, lng: pt.lon, name });
    }
  }

  console.log(`[StreetNames] ${cityId}: Indexed ${grid.size} street points`);

  // Use wider distance for polygon zone centroids (Quebec) vs street segments
  // Longueuil segments sometimes have midpoints 50-80m from OSM road center
  const maxDist = cityId === 'quebec' ? 0.002 : 0.001; // ~220m vs ~110m

  const updateName = db.prepare('UPDATE street_segments SET nom_voie = ? WHERE id = ?');

  let enriched = 0;
  const update = db.transaction(() => {
    for (const seg of toEnrich) {
      const name = grid.nearest(seg.lat, seg.lng, maxDist);
      if (name) {
        updateName.run(name, seg.id);
        enriched++;
      }
    }
  });

  update();
  console.log(`[StreetNames] ${cityId}: Enriched ${enriched}/${toEnrich.length} segments with real street names`);
  return enriched;
}

/**
 * Enrich all cities that need street names.
 * Runs sequentially to be respectful to Overpass API rate limits.
 */
export async function enrichAllStreetNames(): Promise<void> {
  const cities = ['longueuil', 'quebec', 'gatineau', 'laval'];

  for (const cityId of cities) {
    try {
      await enrichStreetNames(cityId);
    } catch (err) {
      console.error(
        `[StreetNames] ${cityId} enrichment failed:`,
        err instanceof Error ? err.message : String(err)
      );
    }
    // Small delay between cities to be polite to Overpass
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
}
